Upstream/merge v3.1.0
ComposableFi/ibc-go pull request #18
Opened 2022-06-20 07:09 UTC by vjdmhd

## Description
Upgrade code according the upstream cosmos [IBC-Go](https://github.com/cosmos/ibc-go/tree/v3.1.0).

closes: #17 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Check trie new version and `VerifyProof` method replacement
- [ ] Implement `CheckHeaderAndUpdateState` Method of the client state for beefy
- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2022-06-20 09:23 UTC, blasrodri commented on modules/apps/27-interchain-accounts/host/types/keys.go
> +	if len(allowMsgs) == 1 && allowMsgs[0] == "*" {
alternatively use https://pkg.go.dev/strings#EqualFold

2022-06-20 09:26 UTC, blasrodri commented on modules/apps/transfer/types/trace.go
> +		if i < length-1 && length > 2 && fullDenomItems[i] == PortID {
it would be nice to get some comments here on what these conditions imply

2022-06-22 08:11 UTC, seunlanlege requested changes
Naahhh we can't merge this.

2022-06-22 08:12 UTC, seunlanlege commented
Our work should be based on this branch: https://github.com/cosmos/ibc-go/tree/02-client-refactor

2022-06-22 08:12 UTC, closed without merging